### ISSUE TITLE
Pretty output: run the program through prettier 

### ISSUE THREAD

**Issue by mohsen1** [lyft/react-javascript-to-typescript-transform#18]
TypeScript printer is not printing the most beautiful code. We can run the code through prettier as second phase of processing to get nicer output.

**Comment by vincentbel** [comment]
@mohsen1 I use prettier after running this transform, All codes looks OK except the empty line won't be reserved. 

I think it's hard to pass the transformed AST to prettier to format since [it uses `typescript-eslint-parser`](https://github.com/prettier/prettier/blob/105914e45ce7557df34964c4e002ffa3dc97764e/src/language-js/parser-typescript.js#L34).

The workaround I used is using  [jsdiff](https://github.com/kpdecker/jsdiff) to compare original code and the result and add the empty lines back.

**Comment by mohsen1** [comment]
prettier APIs work with raw text too. We can add prettier as a secondary phase of processing [here](https://github.com/lyft/react-javascript-to-typescript-transform/blob/45c5dca1c7de67849a0b0b638966c928f0c22290/src/compiler.ts#L38-L41)

For the CLI we want to proxy all CLI flags of prettier

**Comment by vincentbel** [comment]
@mohsen1 What I mean is:

**original file:**
```ts
import * as React from 'react';

export default class MyComponent extends React.Component {
    render() {
        return <button onClick={this.onclick.bind(this)} />;
    }

    onclick() {
        // ...
    }
}
```


**ts transform result:** (empty lines are stripped now)
```ts
import * as React from 'react';
export default class MyComponent extends React.Component<{
    }, {
    }> {
    render() {
        return <button onClick={this.onclick.bind(this)}/>;
    }
    onclick() {
        // ...
    }
}
```


[**use prettier to format the ts result:**](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAtgBwgJxgAgCp8BDAZ3wCU4SwCAzHCdfAchxrtYG4AdKOAA9sefABM49EgFcANgTCzyFALIBPAMLNsA2PiHwoYitVowAdFqzQEMADzB++Z-gC+AGnyOoLtwD4vJxcOIzgcAAoASkCfX2C4GGkcHzsAI2kYGGh8aA1ZVDAAawBeYBgAC1Qyc2hFAsLzVNQjcIqqyNcAej8+WOdXIOda-KKomLiXTs78c1nBt35XEHcQCEwYVGgyZFASHCYAdwAFPYRtlBIANwhUMWWQchhkKVkyOBXUnFpChIBlTFozQA5sgYDhpO8QGIIGBniRXpDmm88EcvkD0CQ4QiVgArMiCABCXyKfxI6DgABlmnAsW8VhAMpgMgAmWmQgE4ZHIEAwNSYOBkMA4VDre6YYWwADqtwqyAAjAAGBUrcUQN6Sr6YbnigVhS40lYcACO0lQHFRJHRmKQLzpIDe6FQoPBkLIwNkcAAitIIPBnRCVjASKlpWJZUgACyBr6ofJQIFWDHcqA2e7SN4AFWD51tcFcriAA)(prettier won't add empty lines)
```ts
import * as React from 'react';
export default class MyComponent extends React.Component<{}, {}> {
    render() {
        return <button onClick={this.onclick.bind(this)} />;
    }
    onclick() {
        // ...
    }
}
```

Prettier won't add empty lines for us, it will just respect the empty lines in original file.

**Comment by mohsen1** [comment]
Preserving empty lines is pretty difficult. I remembered somewhere in TypeScript issue tracker they mentioned why they don't preserve the empty lines 

We can probably do it as a transform phase on top of prettier

**Comment by dsherret** [comment]
Yeah, right now the printer doesn't really take node positions into account (see [here](https://github.com/Microsoft/TypeScript/blob/9436b1cc0b1b67be23568e2c9bc715f5aec8ef92/src/compiler/emitter.ts#L322) and below in that file) so all the newlines will disappear and the formatting will be according to the printer.

Side note: FWIW, you might want to consider checking out [ts-simple-ast](https://github.com/dsherret/ts-simple-ast). It can be used to more easily do code manipulations in TypeScript. It will do the edits on the source file text directly so it won't cause any formatting changes—new lines will be preserved. I'm slowly working on refactoring the writing so that it can be easily configured with formatting options. The downside is that it's not as performant as doing transformations on the AST directly, but it's not too bad.

Also, this react-javascript-to-typescript-transform is an excellent idea! It's good to be able to automate helping people switch over to TypeScript.
